language: ruby
rvm:
  - 1.9.3
env:
  - DB=mysql
script:
  - bundle exec rake --trace spec:unit
#  - bundle exec guard-jasmine
before_script:
  - mysql -e 'create database `nhs-patientlist-test`;'
  - bundle exec rake --trace db:setup
